### ISSUE TITLE
Broken install in conda for biorbd-casadi and python3.7

### ISSUE THREAD

**Issue by fbailly** [pyomeca/biorbd#144]
When installing biorbd-casadi from conda-forge in python 3.7, the package is installed in /lib/python3.8/site-packages/
Moving the folder to python3.7/site-packages does not do the trick, there are some .so missing !

**Comment by pariterre** [comment]
Hello!
biorbd-casadi is no longer existing. The proper to force casadi backend on conda is to install it like this:
conda install biorbd=*=*casadi* -cconda-forge

Or to install BiorbdOptim via conda forge (it will download the proper backend by itself).

The doc will soon be updated
