### ISSUE TITLE
[REVIEW] Improvements to MATLAB installation

### ISSUE THREAD

**Issue by abhishektha** [pyomeca/biorbd#173]
From self-compiling on Windows with default, it looks like the MATLAB .mexw64 file is put in C:\Program Files\MATLAB\{version}\toolbox\, but this is not in the default MATLAB search path (at least with the R2020a version I'm running).

I would suggest putting a note in the MATLAB section of the documentation to ensure that the .mexw64 file is in the search path with the command:
```matlab
oldpath = path;
path(oldpath, 'C:\Program Files\MATLAB\R2020a\toolbox\biorbd_matlab');
```

This allows biorbd to be found globally. I believe this has to be run every time MATLAB is restarted, unless this snipped is added to ```startup.m```

If possible, I also think it would be a good idea to maintain a copy of the compiled MATLAB version of biorbd on [MATLAB File Exchange](https://www.mathworks.com/matlabcentral/fileexchange/). This increases visibility for biomechanics MATLAB users.

**Comment by abhishektha** [comment]
linking to JOSS Review openjournals/joss-reviews#2562

**Comment by pariterre** [comment]
Hi @abhishektha 
Thanks for the suggestion! The PR #176 added such warning

For the copy in MATLAB File Exchange, this is something that was discussed here https://github.com/pyomeca/ezc3d/issues/24 (another project that I drive called ezc3d). Guys from Opensim strongly vetted against it pointing out the fact that it quickly runs out-of-date, and considering the numerous version of MATLAB (2 per years on each OS), it creates a huge burden... In the past I tried to find automatic CI for that (such as conda-forge), but never found one which had matlab development toolkit...

**Comment by abhishektha** [comment]
Great, thanks @pariterre ! Yes there are definitely downsides to MATLAB File Exchange, hopefully someone develops a CI for it in the future!
