### ISSUE TITLE
mesh file parameters

### ISSUE THREAD

**Issue by jfslin** [pyomeca/biorbd#232]
Would you be able to point me to some documentation on mesh support in biorbd? I wasn't sure if I was looking in the right places, but didn't see anything in the class files or old issues

I tried loading an .stl file and wasn't able to. I also have triangles saved as .obj files and those loaded successfully using `meshfile .[filename.obj]`, but I was wondering if there's a way to scale/rotate/position them on the kinematic chain? In addition, is there a way to make the meshes oblique/solid colour?  

If there's no specific way to rotate/scale the meshes, is there a way to turn on placeholder segments? I would like some lines to connect all the frame centres so it's a bit easier to see the whole body as it's moving. 

Thank you. 

![image](https://user-images.githubusercontent.com/24707634/133683837-dc6ffddd-9301-4e43-a588-f56334156333.png)

**Comment by pariterre** [comment]
Dear @jfslin 
The newest version on biorbd should read STL files. I am not sure if I already pushed it to conda though, as it was like last week that I added that feature! VTP and obj files should also work just fine.

There is currently unfortunately no way to rotate them with respect to a body segment. If you need that, I would suggest to create a virtual segment with the desired body as parent, and rotate this virtual segment with RT in the bioMod. Same thing for position. For scaling, I don't see an easy way to do so as is right now, but I think it could be easily added to the bioMod... I am currently very busy, but I may have a try (if I do, I will implement the rotation and positioning of the mesh, as it would be a similar time to implement!).

If you don't use meshfile, you can define edges by hand by writing a series of mesh in the segment. For instance :
```segment
    mesh 0 0 0
    mesh 0 0 1
    mesh 1 0 0
    mesh 0 0 0
endsegment```
would draw a triangle but without faces.

Speaking of faces, again this is something we added last week so for your last question, yes it is possible to draw actual faces. The color is currently a single one for all the segments, but it would be very easy to store the desired color in the bioMod, if you think it makes sense to add this feature!

Please let me know what you need, and I'll see what I can do!

**Comment by jfslin** [comment]
Hi @pariterre - thanks for the response.

I tried doing an update from conda but it didn't seem to have pulled anything new (but loading obj files using `meshfile` works for me anyway) - it's not urgent though, if I cannot scale the meshes within biorbd, I'm going to leave that for now. I actually am not too interested in meshes at the moment, I just want the kinematic chains visualized so I can see the movement more clearly. Would you be able to point out how I can draw a line connecting each segment, something like:

![image](https://user-images.githubusercontent.com/24707634/133708727-f14bbcbf-6424-4d25-b9ab-b7fe7f515776.png)

Also, this may be the wrong place to ask, but for bioviz, is it possible to plot the c3d file, so I can see the movements of the model markers, as well as the markers that was used for the IK? I see in the bioviz document that I can turn on and off the model markers, but I didn't see anything about the c3d markers. 

Thank you.

**Comment by pariterre** [comment]
Hi again!

For such a model, I would suggest to add the mesh like so:
```
segment
    ...
    mesh 0 0 0
    mesh TRANSLATION_TO_THE_NEXT_SEGMENT
endsegment
```
This should do the trick. They will be fine black wire instead of thick blue lines, but it is very easy to see (that is exactly how I was printing stuff before adding the obj/vtp/stl files). 

Funny enough, plotting c3d markers is also something I added last week, but without the ground reaction force, yet. So yes, it is possible, I will create a release soon so you can pull every new development!

**Comment by jfslin** [comment]
Hm. I had tried running a model with `translation_to_the_next_segment` and ran into some exceptions. I realized I was running an older version of biorbd (1.5.5) and updated everything in conda. Now I can't find biorbd_eigen:

```
Traceback (most recent call last):
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "miniconda3\lib\site-packages\biorbd\__init__.py", line 1, in <module>
    from . import biorbd
  File "miniconda3\lib\site-packages\biorbd\biorbd.py", line 13, in <module>
    from . import _biorbd_eigen
ImportError: DLL load failed while importing _biorbd_eigen: The specified module could not be found.
python-BaseException
```

Seems like I'm missing a library for some reason. Will continue to poke around...

**Comment by pariterre** [comment]
Hi!

The name of the DLLs changed when I allowed to install the eigen back-end and the casadi back-end at the same time. I suggest that you go in the environment folder and do a search of biorbd and remove any old DLLs since you may now have files named biorbd.dll and biorbd_eigen.dll which can confuse Windows!

**Comment by jfslin** [comment]
Hi @pariterre, I wasn't able to find the biorbd.dll or biorbd_eigen.dll files, and ended up just reinstalled miniconda, which fixed the issue. Now...running a model with this segment:

```
    segment    LowerArm_L
        parent UpperArm_L
        rotations    yz
        rtinmatrix 1
        rt
            1 0 0 0
            0 1 0 0
            0 0 1 -0.27198266080162
            0 0 0 1
        mass    1.0069938933548
        inertia
            0.0050087869334809 0 0
            0 0.0046174918925081 0
            0 0, 0.00096268706013828
        com     0 0 -0.11687992888153    
    endsegment
```

has no issue, but once I modify it to:

```
    segment    LowerArm_L
        parent UpperArm_L
        rotations    yz
        rtinmatrix 1
        rt
            1 0 0 0
            0 1 0 0
            0 0 1 -0.27198266080162
            0 0 0 1
        mass    1.0069938933548
        inertia
            0.0050087869334809 0 0
            0 0.0046174918925081 0
            0 0, 0.00096268706013828
        com     0 0 -0.11687992888153    
        mesh 0 0 0        
        mesh TRANSLATION_TO_THE_NEXT_SEGMENT
    endsegment
```

I get the following exception: 

```
Traceback (most recent call last):
  File "PyCharm 2020.3.3\plugins\python\helpers\pydev\pydevd.py", line 1477, in _exec
    pydev_imports.execfile(file, globals, locals)  # execute the script
  File "PyCharm 2020.3.3\plugins\python\helpers\pydev\_pydev_imps\_pydev_execfile.py", line 18, in execfile
    exec(compile(contents+"\n", file, 'exec'), glob, loc)
  File "bioviz_test.py", line 3, in <module>
    model = biorbd.Model('models/nocalibmarkers.bioMod')
  File "miniconda3\lib\site-packages\biorbd\biorbd.py", line 5890, in __init__
    _biorbd_eigen.Model_swiginit(self, _biorbd_eigen.new_Model(*args))
RuntimeError: invalid stod argument
python-BaseException

Process finished with exit code 1
```

It doesn't seem to like the `TRANSLATION_TO_THE_NEXT_SEGMENT` argument.

**Comment by pariterre** [comment]
Hello!
Obviously TRANSLATION_TO_NEXT_SERMENT should be modified for the translation to the next segment 😅

So, if your next segment has a translation (fourth column of RT) equals to 0 0 -0.3
Then the mesh line should read
mesh 0 0 -0.3

Enjoy!

**Comment by pariterre** [comment]
Hi again @jfslin 

I added the capability to modify the mesh from the bioMod (meshcolor, meshscale, meshrt, to respectively modify the color of a particular mesh, the XYZ scaling of a particular mesh and the rotatranslation wrt ot parent of a particular mesh) in #233 . These tags can be added after the declaration of the mesh in the segment section as such: 

```c
segment seg1
    meshfile PATH_TO_MESH_FILE
    meshcolor 1 0 0 // Give a red color to the bones
    meshscale 2 1 1 // X is twice as big
    meshrt pi/2 0 0 xyz 0 0 1  // Give a pi/2 rotation about x axis and translate of 1 on Z
endsegment
```

I have to create a release and then create a release for bioviz as well (for the color management), but it should be fully available in conda in few days :)

**Comment by jfslin** [comment]
@pariterre - embarrassingly, I had obviously thought that `translation_to_next_segment` was an actual command that automatically determined the next segment. Once I've corrected that, I was able to generate the appropriate mesh lines. And thank you for putting in the scaling features, looking forward to it.
