### ISSUE TITLE
Mesh scaling and color Python

### ISSUE THREAD

**Issue by RVSagar** [pyomeca/biorbd#253]
Hi,

I had a question about mesh scaling and color modifications through the Python interface.

In particular, I am running this minimal example (adapted from #245) and trying to pass in a scaled and colored mesh to SegmentCharacteristics. The mesh gets passed on fine and gets written to the .bioMod file but the mesh scale and color do not. Any ideas?

```python

import numpy as np
import biorbd
import bioviz

# Defining two identical segments for testing
name_first = "First_segment"
name_second = "Second_segment"
parent_first = "ROOT"
parent_second = "Pelvis"
translations = "xyz"
rotations = "xyz"
ranges = []
roto_trans = biorbd.RotoTrans(np.array([1, 2, 3]), np.array([4, 5, 6]), "xyz")
mass = 10
com = biorbd.Vector3d(1, 2, 3)
inertia = biorbd.Matrix3d(1, 2, 3, 4, 5, 6, 7, 8, 9)

#mesh with modified scale and color
mesh = biorbd.Mesh()
mesh.setPath(biorbd.Path("unit_cube.obj"))
mesh.scale(biorbd.Vector3d(2, 1, 1))
mesh.setColor(biorbd.Vector3d(0.5, 0.5, 0.5))

char = biorbd.SegmentCharacteristics(mass, com, inertia, mesh)

# Create an empty model and add the two segments
model = biorbd.Model()
model.AddSegment(name_first, parent_first, translations, rotations, ranges, ranges, ranges, char, roto_trans)
model.AddSegment(name_second, parent_second, translations, rotations, ranges, ranges, ranges, char, roto_trans)

# Write the model and read back
biorbd.Writer().writeModel(model, "test_model.bioMod")
test_model = biorbd.Model("test_model.bioMod")

bioviz.Viz(loaded_model=test_model).exec()

```

I've attached the unit_cube.obj mesh as a zip file.
[unit_cube.zip](https://github.com/pyomeca/biorbd/files/7893053/unit_cube.zip)

Thanks for your help!

**Comment by pariterre** [comment]
Hi @RVSagar 
This is actually a bug from the method "Writter"... this is unfortunately a method that did not follow the latest development (as I never use it, so completely forgot about it)!
I am currently finishing my PhD (thesis to be submitted in a month and a half) so I won't be able to fix that minor bug in the mean time... 

If you need to change the color in a loaded version from .bioMod, I would suggest to either do a quick find and replace (very ugly hahaha) or actually add the color in the Writter method in the C++ side (which should not be complicated actually)

Sorry about that!

**Comment by RVSagar** [comment]
Hi @pariterre,

Thanks for the tip, I see that adding a few lines [here](https://github.com/pyomeca/biorbd/blob/master/src/ModelWriter.cpp#L75) would solve the issue (for the new `meshscale`, `meshcolor` and `meshrt` properties). I can make a PR after I do it locally. I'll leave the issue open for visibility.

All the best with the thesis!

**Comment by pariterre** [comment]
If you need biorbd to be available on conda soon, feel free to ask, I'll make a release :)

**Comment by RVSagar** [comment]
@pariterre thanks, whenever you get a chance to make a release that would be great :), however no rush/pressure from me, I know you're busy and I can work with compiling biorbd!
