### ISSUE TITLE
inertia matrix

### ISSUE THREAD

**Issue by nashmit** [pyomeca/biorbd#264]
To what point, the inertia matrix must be computed? Is it relative to the local reference of the current segment or relative to the center of mass? From documentation is not clear which one is required by the input format.

Thanks!

**Comment by pariterre** [comment]
Hi @nashmit !

Do you mean the one you provide in the bioMod file or the one returned by the call to the method?
The first is expressed in the local reference frame with respect to the center of mass of the segment.
The second is expressed in the universe reference frame with respect to the global center of mass.

If you know how we could rephrase the doc from the two lines above, I encourage you to update the documentation and Pull Resquest it! :)

Hope this helped!

**Comment by nashmit** [comment]
I was referring to the inertia matrix that one must provide as input into the 'bioMod' file. 

Thanks for the clarification!
