### ISSUE TITLE
Sensitivity computation / possible memory leak

### ISSUE THREAD

**Issue by nashmit** [pyomeca/biorbd#267]
Hi!

I have used biorbd as a way to define complex dynamical systems as a generic external RHS ODE equation for a toy optimal control implementation build on top of CasADi which makes use of the Callback interface. 

This involves computing Hessian and Jacobian in a numerical way. All works almost perfectly, in the sense that I get correct results but the computation time is insane. On top of that, I also think somewhere in the code there is a leak since during the optimal control the memory is increasing very fast ( get to 4GB in 10-15 minutes for a simple inverted pendulum problem ) and this happens only when I use the biorbd for the RHS so, my guess is that it might be a problem on biorbd level. Non the less, I am still testing it.

My question for you is.... how do you compute the sensitivity? I suppose you have done it using automatic differentiation and not finite difference, right? ( I've seen the video that introduces your framework and it seems that the process is quite fast not to be AD ) Can you point me to the place this process is done?

Thanks!

**Comment by pariterre** [comment]
Hi there!

If you ever find out which function creates a memory leaks, please tell me I'll correct this!

For the sensitivity, I am indeed doing it using casadi. To load casadi instead of eigen backend (assuming you are using python) you do:
`import biorbd_casadi as biorbd` 
Then the backend will be from casadi ;)

Please note that some features from RBDL and biorbd are disabled in casadi's backend

Furthermore, if you are doing optimal control, I suggest that you have a look at bioptim, which is the optimal control solution that we developed :)

**Comment by nashmit** [comment]
Ok, so you do have automatic differentiation but by using operator overloading in c++ You're not using CasADi's functionality for this task. 

Thanks for letting me know where to look for the implementation!

My MSc project involves also doing some work at the level of the optimal control module so I can't use other implementations, nonetheless, I can always study them :D

**Comment by pariterre** [comment]
I did the casadi implementation in RBDL actually. Every "Rigidbody::Math::Vector" is ultimately either an eigen vector or a casadi vector. Every functions which are used in RBDL were interface in casasdi so they look the same as an eigen call (except for solving linear system). 
So, as a user, switching from one to the other is basically just compiling using the chosen backend. 

In the biorbd package on conda, both version are compiled. This is why you can use both at the same time. Please note that they are however incompatible (you can use both at the same time but not feed one into the other). You can convert though the casadi calls into casadi function to get numerical values. This is beyond the scope of helping here though and if you are not aware how to create casadi function, I suggest (again :P) that you have a look at bioptim, and search for "Function" (with a capital F) or use the `biorbd_casadi.to_casadi_function` for an "easy interface"
