### ISSUE TITLE
Problem with bioviz

### ISSUE THREAD

**Issue by yugiero** [pyomeca/biorbd#280]
Hi! I'm trying to run a code that has been working some time ago. It is just using bioviz to display the motion of a model. Even only displaying the tpose [lukas.txt](https://github.com/pyomeca/biorbd/files/8986616/lukas.txt) though results in the following error:
![grafik](https://user-images.githubusercontent.com/95051226/175814522-6cb95ade-44b4-4427-9653-f83af6059a5f.png)

The pendulum bioptim example works and biorbd is on 1.8.7, bioviz on 2.1.7. What is wrong with my biomod file?

**Comment by pariterre** [comment]
Hi there!
This seems related to a bug in bioviz and not from your model, I have a look and keep you posted!
