### ISSUE TITLE
getting COM for the whole model

### ISSUE THREAD

**Issue by MahsaP** [pyomeca/biorbd#289]
Hi,

How can I get the center of mass for the whole model? Right now the com is not updated. Can you give me an example. 
```

for i, targetMarkers in enumerate(markersOverFrames):
    kalman.reconstructFrame(model, targetMarkers, Q, Qdot, Qddot)
    # Proceed with the inverse dynamics
    Tau = model.InverseDynamics(Q, Qdot, Qddot)
    q_recons[:, i] = Q.to_array()
    com = model.CoM(q_recons[:, i])
    out_com = com.to_array()
    com_x+=[out_com[0]]
    com_y+= [out_com[1]]
    com_z+= [out_com[2]]
    com_x = np.array(com_x)
    com_y = np.array(com_y)
    com_z = np.array(com_z)
```
Thanks.

**Comment by MahsaP** [comment]
The joint angles are changing but the COM returns the same value over iterations. For example, I have a data for squat motion and would like to see the trajectory of COM.

**Comment by pariterre** [comment]
Can you give me the output for: 
```python
com = np.ndarray((3, len(markersOverFrames))))
for i, targetMarkers in enumerate(markersOverFrames):
    kalman.reconstructFrame(model, np.reshape(markers_in_c3d[:, :, i].T, -1), q, qdot, qddot)
    com[:, i] = model.CoM(q.to_array()).to_array()
```

Because, this works just fine here..

**Comment by MahsaP** [comment]
I get this result where the numbers in each row do not change a lot. 
![image](https://user-images.githubusercontent.com/12606874/190253961-f1c458f4-3fcb-44d9-8f4a-cfe2beff4b10.png)

**Comment by pariterre** [comment]
Not changing a lot is not the same as not changing... What is your frame rate? If it is 100 frames per second, 23 frames is not even a third of a second. It makes sense that it does not change a lot... can you graph these results using matplotlib or copy-paste the full values over the trial?

**Comment by MahsaP** [comment]
I should have plotted this one. 
![image](https://user-images.githubusercontent.com/12606874/190257611-ad5c02e6-30c5-422d-ac02-e0d280c88a08.png)
I do get the correct trajectory.
Thanks a lot.
