### ISSUE TITLE
Add ligaments

### ISSUE THREAD

**Issue by aceglia** [pyomeca/biorbd#296]
@pariterre I think it must not be too difficult if it's done the same way as muscles right? Different models can be implemented and defined the same way as muscles with insertion, origin, slack length, etc...

**Comment by pariterre** [comment]
ligaments are basically muscles in a modelling stand point. Addind this would be a matter of creating a parallel structure to the muscles with relevant name. As far as I am concerned, there is not pitfall to this as muscles can be used as template. This could be considered as a student project I think

**Comment by aceglia** [comment]
@pariterre you can close this one
