### ISSUE TITLE
missing euler-cardan sequence yxy

### ISSUE THREAD

**Issue by Ipuch** [pyomeca/biorbd#300]
This is an important sequence of ISB:

![image](https://user-images.githubusercontent.com/40755537/195426686-b4665998-a067-4fe3-aa40-c5e53f2a4d35.png)

**Comment by pariterre** [comment]
YXY is actually ZYZ when the vertical axis is Z (instead of Y as prescribed by ISB, but is contrary to default in biorbd)

**Comment by Ipuch** [comment]
done in #314
