### ISSUE TITLE
Conda install PackagesNotFoundError

### ISSUE THREAD

**Issue by piaoziyue** [pyomeca/biorbd#316]
Hi,
When I am installing biorbd, it always shows 
PackagesNotFoundError: The following packages are not available from current channels:
But I have already added conda-forge into my conda channels, and I have stuck on the problem for a week and cannot figure out the solution. Can you help me about that? thanks a lot

Environment:
python 3.9.12
platform : MacOSX-arm64
conda version : 22.9.0

**Comment by pariterre** [comment]
Dear @piaoziyue 
Indeed, there is no package yet for macosx_arm64. I am suppose to add this in a very near future (we discussed this very topic yesterday with my supervisor). I'll let you know when it is done!

**Comment by piaoziyue** [comment]
Dear @pariterre 
Thanks for your help! Look forward to the new version.

**Comment by pariterre** [comment]
Dear @piaoziyue 
After a LOOOOONG journey, I finally managed to add osx_arm64 to biorbd! This should work now :D
