### ISSUE TITLE
Error when shape of com is (n,0)

### ISSUE THREAD

**Issue by AnaisFarr** [pyomeca/biorbd#318]
this creates a bug if we give an 1D-array.
```python3 
com = np.nanmean(self.center_of_mass, axis=1)[:3]
```

**Comment by pariterre** [comment]
Dear @AnaisFarr 
Could you be a bit more explicit? What kind of bug? Also in what context (Can you provide a small yet meaningful example of what fails)?

**Comment by AnaisFarr** [comment]
I try to create a planar model from a 3D-model. So I used biorbd.model_creation but the inertia parameters created a bug when I wanted to print it to a bioMod file because the center of mass of my 3D-model was a 1D-array. So I added [:, np.newaxis] and it works.

Here my code: 

```python3
model2D["Pelvis"] = SegmentReal(
    name="Pelvis",
    translations=Translations.XY,
    rotations=Rotations.Z,
    inertia_parameters=InertiaParametersReal(
        mass=model3D.segments()[0].characteristics().mass(),
        center_of_mass=model3D.segments()[0].characteristics().CoM().to_array()[:, np.newaxis],
        inertia=model3D.segments()[0].characteristics().inertia().to_array()))
```

And the errors:
```python3
File "/home/lim/miniconda3/envs/anais_bioptim/lib/python3.10/site-packages/biorbd/model_creation/inertia_parameters_real.py", line 82, in __str__
    com = np.nanmean(self.center_of_mass, axis=1)[:3]
  File "<__array_function__ internals>", line 200, in nanmean

**Comment by AnaisFarr** [comment]
I tried to create a new model by modifying the information of an old model. So I used biorbd.model_creation and InertiaParametersReal() to transfer the inertia's information of my old model to my new model.
```python3
model2D["Foot"] = SegmentReal(
    name="Foot",
    parent_name="Leg",
    rotations=Rotations.Z,
    segment_coordinate_system=SegmentCoordinateSystemReal.from_euler_and_translation(
        (-np.pi / 2, 0, 0), "xyz", (0, 0, -0.43)),
    inertia_parameters=InertiaParametersReal(
        mass=model3D.segments()[11].characteristics().mass()*2,
        center_of_mass=model3D.segments()[11].characteristics().CoM().to_array()[:, np.newaxis],
        inertia=model3D.segments()[11].characteristics().inertia().to_array()*2))
```
It worked, but the model can't be read as a bioMod file because of the form of the inertia's parameters (I can open the bioMod file without the inertia and with the mass and the CenterofMass). Here the bioMod file of the new model that I created and the error I received when I tried to read the bioMod file.

```python3
segment Foot
	parent Leg
	RT -1.571 0.000 -0.000 xyz 0.000 0.000 -0.430
	rotations z
	mass 8.36
	CenterOfMass 0.00000 0.00000 -0.20260
	inertia_xxyyzz [0.1702 0.     0.    ] [0.     0.1702 0.    ] [0.     0.     0.0122]
endsegment
```
```python3
  File "/home/lim/miniconda3/envs/anais_bioptim/lib/python3.10/site-packages/biorbd/biorbd.py", line 7120, in __init__
    _biorbd_eigen.Model_swiginit(self, _biorbd_eigen.new_Model(*args))
RuntimeError: stod
```

**Comment by pariterre** [comment]
Dear @AnaisFarr 
I do not know why it worked, as it should have failed haha 
Nevertheless, you .bioMod file can easily be edited. You just have to remove the `[]` and the `0`, so it reads:
`inertia_xxyyzz 0.1702 0.1702 0.0122`
