### ISSUE TITLE
Angular momentum around contact points

### ISSUE THREAD

**Issue by jfslin** [pyomeca/biorbd#329]
I have a full body biorbd kinematic/dynamic model that I am using in Python. I am interested in the full body angular momentum around contact points (ie the feet) during perturbation when stationary. I have a few questions:

1) I have a 20 segment model. I found the `CalcSegmentsAngularMomentum` function, but it gives me a 47 length array of 3x1 vectors. What exactly does this function return? 

Reading the docs, it seems to simply that I am getting the AM around each segment...so should this also be a 20 long 3x1 vector? https://pyomeca.github.io/Documentation/biorbd/classbiorbd_1_1rigidbody_1_1Joints.html#a923f4fb057e3d7b010a92f8ee9fd3c9e

```
mdl
Out[0]: <biorbd.biorbd.Model; proxy of <Swig Object of type 'BiorbdEigen3::Model *' at 0x000002B28ECA5990> >

mdl.nbSegment()
Out[1]: 20

am_curr = self.model.CalcSegmentsAngularMomentum(q[:, i], dq[:, i], ddq[:, i], True) 
len(am_curr)
Out[2]: 47
```

2) If I understand correctly, `CalcAngularMomentum` calculates the AM of the entire body around the whole model's COM and mass. Does `CalcSegmentsAngularMomentum` calculate the AM only around each segment? Or is the whole body's AM around that particular segment's COM? Given the conversation at https://github.com/pyomeca/biorbd/issues/257#issuecomment-1024939913, my understanding is that `CalcSegmentsAngularMomentum` would give me the AM around each given segment, so not quite what I am looking for yet. Is there a way to set the COM that `CalcAngularMomentum` rotates around so it's not around the model's COM, but rather around a specific segment? 

Thank you.

**Comment by pariterre** [comment]
Dear @jfslin 

1.  The short answer is a "segment" in biorbd is translated into N-Degrees-of-freedom bodies into rbdl. Meaning that you always get as many Bodies as you have degrees of freedom. I therefore suspect you have segments that declares more than one translations or rotations. To get the "segment" value, you simply take the last one for that particular segment. For instance, if your model has 3 segments (all of them declaring 2 rotations), then the AM of the second segment is the 4th row (second being the values for the 1st segment and last being the values for the last segment). This is a bit confusing, but there is no easy workaround for this as sometimes you would need intermediate values. 

2. There is no internal way to do that, but you can of course recompute the AM to be evaluated anywhere you want using the parallel axis theorem. 

Cheers!

**Comment by jfslin** [comment]
@pariterre Thank you for the quick response!

1. Ah:
```
mdl = ik.model
mdl.nbQ()
Out[3]: 47
```
There, that's the 47. Okay. So "segment" in this case is referring to joints/reference frames etc., while `nbSegments()` gives me the number of rigid bodies that makes up my model. 

2. Thanks for including the bit about the parallel axis theorem. I was wondering if that was sufficient. So to recap, I should run `CalcSegmentsAngularMomentum`, keep only the vectors that are at the end of the body's "chain" for the cases of concentric joints, then use `CoMbySegment` and the segment masses to move all the individual AMs to the contact point in question via parallel axis theorem. 

Perfect. I will get on that. Thank you.

**Comment by pariterre** [comment]
Yup, sounds good, the only thing about 2) is that you probably willl have to rotate the AM after transporting, unless you want it aligned with the global reference frame!

**Comment by jfslin** [comment]
Noted. Thanks a lot for your help.
