### ISSUE TITLE
Correct presentation of joint angles from biorbd?

### ISSUE THREAD

**Issue by MahsaP** [pyomeca/biorbd#334]
Hi,

I have a Vicon data where an IOR marker set is used for a human motion. I was able to get angles from biorbd. The angles which are reported are not the joint angles I expect. How can I to get the correct joint angles for example for the middle trunk? When I look at the motion the middle trunk is not moving but the results reported by biorbd shows a considerable range of motion for the middle trunk? The following figure shows the output I get from biorbd for each segment!
![image](https://github.com/pyomeca/biorbd/assets/12606874/263c4155-6152-4962-81f6-a2c9259e8d7c)

**Comment by pariterre** [comment]
Hi @MahsaP !
What do you mean by `When I look at the motion the middle trunk is not moving`? Based on the data reported I say that the trunk was definitely moving!

Please provide me with a minimal script you ran so I can have a look at your code and also a copy of you bioMod file

Cheers

**Comment by MahsaP** [comment]
Here is the code for inverse kinematics: 

```
import numpy as np
import biorbd
import csv
import os
import sys

# lab-wide common libraries
import temporal_segments
from load_csv import load_csv
import configurations_commons
import utilities_file_loading
import utilities
from ezc3d import c3d

show_visual = True

try:
    import bioviz

    bioviz_found = True
except ModuleNotFoundError:
    bioviz_found = False


def ReadPoint(c, label):
    pointlabels = c['parameters']['POINT']['LABELS']['value']
    pointcoordinates = None
    # print(pointlabels)
    data = c['data']['points'][:, :, :]
    NUM: int
    for NUM, x in enumerate(pointlabels):
        if x == label:
            pointcoordinates = data[0:3, NUM, :]

    # if pointcoordinates is None:
    #     print(label)

    return pointcoordinates


# This examples shows how to
#     1. Load a model
#     2. Generate data (should be acquired via real data)
#     3. Create a Kalman filter
#     4. Apply the Kalman filter (inverse kinematics)
#     5. Plot the kinematics (Q), velocity (Qdot) and acceleration (Qddot)
#
# Please note that this example will work only with the Eigen backend.
# Please also note that kalman will be VERY slow if compiled in debug
#

# biorbd Kalman filter expects the markers in the same order as the bioMod file
markerLabels = ['LV5', 'L_IAS', 'L_IPS', 'R_IAS', 'R_IPS',  # Pelvis
                'R_FLE', 'R_FME', 'R_FTC',  # Thigh_R
                'L_FLE', 'L_FME', 'L_FTC',  # Thigh_L
                'R_FAL', 'R_TAM', 'R_TIB',  # Shank_R
                'L_FAL', 'L_TAM', 'L_TIB',  # Shank_L
                'R_FCC', 'R_FM1', 'R_FM5',  # Foot_R
                'L_FCC', 'L_FM1', 'L_FM5',  # Foot_L #'L_FM1',
                'LV1', 'LV3', 'TV10', 'SXS',  # MiddleTrunk
                'CV7', 'L_SAE', 'R_SAE', 'SJN', 'TV2',  # UpperTrunk
                'R_HLE', 'R_HME', 'R_HUM',  # UpperArm_R
                'L_HLE', 'L_HME', 'L_HUM',  # UpperArm_L
                'R_RSP', 'R_USP',  # LowerArm_R
                'L_RSP', 'L_USP',  # LowerArm_L
                'R_HM2',  # Hand_R
                'L_HM2',  # Hand_L
                'L_HEAD', 'R_HEAD', 'SGL'  # Head
                ]

# Load a predefined model
model = biorbd.Model("models/mahsa_IOR_whole.bioMod")
nq = model.nbQ()

import ezc3d

c3d = ezc3d.c3d("data/perturbed1.c3d")

markers = []
for i, label in enumerate(markerLabels):
    markers.append(ReadPoint(c3d, label))

markers = np.asarray(markers)
markers = np.moveaxis(markers, 1, 0)

poshead_x = markers[0]
poshead_y = markers[1]
poshead_z = markers[2]
pos_x = poshead_x[11, :]
pos_y = poshead_y[11, :]
pos_z = poshead_z[11, :]

# Dispatch markers in biorbd structure so EKF can use it
markersOverFrames = []
for i in range(markers.shape[2]):
    markersOverFrames.append([biorbd.NodeSegment(m / 1000.0) for m in markers[:, :, i].T])

# Create a Kalman filter structure
freq = 100  # Hz
noiseFactor = 1e-6
errorFactor = 1e-5
params = biorbd.KalmanParam(freq, noiseFactor, errorFactor)
kalman = biorbd.KalmanReconsMarkers(model, params)

# Perform the kalman filter for each frame
Q = biorbd.GeneralizedCoordinates(model)
q_recons = np.ndarray((model.nbQ(), len(markersOverFrames)))

try:
    os.remove("result/" + 'q_human.csv')
except OSError:
    pass

t_store = []
t_plt = []

for i, targetMarkers in enumerate(markersOverFrames):
    kalman.reconstructFrame(model, targetMarkers, Q, Qdot, Qddot)
    # Proceed with the inverse dynamics
    Tau = model.InverseDynamics(Q, Qdot, Qddot)
    q_recons[:, i] = Q.to_array()


    with open("result/" + 'q_human.csv', 'a', encoding='UTF8', newline='') as f:
        writer = csv.writer(f)
        data = q_recons[:, i].tolist()
        timestamp = i / 100.0
        data.insert(0, timestamp)
        t_store += [timestamp]
        # write the data
        writer.writerow(data)

        t_plt += [timestamp]




import matplotlib.pyplot as plt

plt.figure()
for i in [7, 12, 15, 20, 23]:
    plt.plot(t_plt, q_recons[i, :])
plt.xlabel("time(sec)")
plt.ylabel("Joint Angles(rad)")
plt.legend(["hip", "knee", "ankle", "middleTrunk", "upperTrunk"], loc="best")

# Animate the results if biorbd viz is installed
if bioviz_found and show_visual:
    b = bioviz.Viz(loaded_model=model)
    b.load_movement(q_recons)
    b.exec()
```

**Comment by pariterre** [comment]
Could you also send my a c3d file. You can send it via email if you prefer

**Comment by pariterre** [comment]
@MahsaP 
Based on the biorbd reconstruction vizualized using bioviz, on the C3D file you provided me, the subject is performing repeated squats which is in accordance I think with the graphs. Are you sure the video you watching and the C3D are actually the same trials?

**Comment by MahsaP** [comment]
@pariterre Thanks for looking at the code. Yes I am sure. The upper body is moving a little bit. For example, based on the graph above the middle trunk is moving around 60 deg while in practice it is not bending. If you look at the following screenshot it is flat: 
![image](https://github.com/pyomeca/biorbd/assets/12606874/63401d34-4bc6-4a44-b59e-62b96f60480e)


Also, one thing that I am just confused here is that when the person starts at the standing pose all the angles must be zero but there is some offset, and I am not sure how to present ankle, knee and hip angles properly if my model starts from a fix foot on the ground. Do you know what is the transformation between the biorbd angles to that model? I came up with something for ankle, knee, and hip and I am not sure if it is correct but do not know what to do for the upper trunk and the mid trunk!

**Comment by MahsaP** [comment]
@pariterre 

Thanks a lot for your detailed explanation.

To make the bioMod model I used a few trials from one the trials captured from Vicon that the participant did not move and they were at the static posture. Then I used lua model converter from IOR marker set and from the lua file I created the bioMod file. It seems my static trial might have caused the error. 

Is there any recommendation to extract the static trial?

**Comment by pariterre** [comment]
The static trial should be either in T-pose or in a relax position (arms almost rested along the body). Using the mean of the data is trickier than it seems as a slight movement of the subject can cause great damage to the resulting model. I personnally never use more than 5 to 50 frames during my static trial, which is long enough to mitigate the electric noise of the camera while being short enough to not pick-up movement such as respiration or natural sway.

For the converter of lua model to bioMod, I don't see major issues with that approach

**Comment by pariterre** [comment]
In order to convince yourself that your static trial is good (and the underlying model too), you can reconstruct the static trial and it should be almost perfect

**Comment by MahsaP** [comment]
@pariterre 

Thanks a lot for your explanation. I generated a new model. But cannot get the output you showed above.
![image](https://github.com/pyomeca/biorbd/assets/12606874/0311ee3e-7817-4a7c-86dd-fb2dcc5e9c7e)

I also used the same method as yours. 
![image](https://github.com/pyomeca/biorbd/assets/12606874/8c2e85ce-74f9-4d1d-ac3b-6291fd75e456)

**Comment by pariterre** [comment]
Are you talking about the red markers? If so, I added a line before the "b.exec()" which is `b.load_experimental_markers(markers / 1000)`

**Comment by MahsaP** [comment]
@pariterre yes thanks a lot.

**Comment by NicolasGrandin** [comment]
Hi everyone !

I'm really interested by your approach since I recorded subjects too with a full body plug-in gait.
Is it possible to share your code since I'm new to biorbd and I'm struggling with it please ?

Thank you in advance and I wish you a very good day !

**Comment by pariterre** [comment]
Dear @NicolasGrandin !

You will find an example on how to reconstruct kinematics using biorbd over here: https://github.com/pyomeca/biorbd/blob/master/examples/python3/inverseKinematicsKalman.py

Please note, that biorbd, by virtue of using Generalized Coordinates, will not emulate the behavior of the Plug-in-Gait. If your goal is to match the results from PiG, I suggest to use PyCGM (https://pycgm2.netlify.app/cgm/cgm1.1/). 
If ressembling the PiG is enough, I am working (part-time) on using PiG in a kinematic chain manner. You can find the source code here: https://github.com/cr-crme/walkerKinematicReconstruction
Please note it is an internal project... So it is not as near much documented as a proper project and probably still buggy!

If you need further assistance, you are welcomed to open a new issue!

**Comment by NicolasGrandin** [comment]
Dear @pariterre 


Thank you very much for your exhaustive information !
I'm sorry for not being as exhaustive as you.

Indeed, I'm my goal is to compare from mobile data (from IMUs and a forces from pressure insoles) with laboratory data (VICON and AMTI force plates) for inverse dynamic analysis (net joint forces and moments without muscles in the model).

From what I understand, I can use biorbd for the IMUs and maybe for the pressure insoles too right ?


Thank you in advance,
Nicolas

**Comment by pariterre** [comment]
@NicolasGrandin 
Please open a new issue for this continuation of conversation so @MahsaP  don't get too spammed!
