### ISSUE TITLE
Set Symbolic markers

### ISSUE THREAD

**Issue by Ipuch** [pyomeca/biorbd#344]
Following #343 an alternative would be to set symbolic markers from Python @SamHybz.
This sould be only a matter on 30 minutes for @pariterre to add a method that does something like,

``` python3
model = biorbd.Model(path/...)
model.setMarker(my_mx)
```

**Comment by pariterre** [comment]
Fixed in #347 
setMarker necessitate the index of the marker to change. Any other changes apart from the position is disregarded 
Cheers :)

**Comment by Ipuch** [comment]
Nice! Thanks 🙏 
@samhybz ready for next level optimizations 💪🏻

**Comment by SamHybz** [comment]
Thanks! 😲 
Will try that ASAP!

**Comment by pariterre** [comment]
@SamHybz 
Do you need a release or you are able to build biorbd from the sources?
