### ISSUE TITLE
MuscularJointTorque function, problem with Casadi argument

### ISSUE THREAD

**Issue by Kilperic13** [pyomeca/biorbd#98]
Hello there !

After the #96 issues, I have an other problem. So, I have the same characteristic than this issues : My operating system is Ubuntu (Linux), I work on PyCharm editor (version 2019.3.3),  I am using the Python 3.7.6 binder. I compute this issue branch #97 and it solve my precedent problem with setActivation.

But now, I have the same problem with the function `muscularJointTorque`.
I show you an example : 
```python
model = biorbd.Model("/home/path_model")
Nb_Muscles = model.nbMuscleTotal()
Act = MX.sym('Act', Nb_Muscles)
w = [Act]
ubw = [1] * Nb_Muscles
lbw = [0] * Nb_Muscles
w0 = [0.5] * Nb_Muscles
State = MX.sym('St', model.nbQ() + model.nbQdot())
w = [Act]
ubw = [3.14] * (model.nbQ() + model.nbQdot())
lbw = [-3.14] * (model.nbQ() + model.nbQdot())
w0 = [0] * (model.nbQ() + model.nbQdot())
VecSDyn = biorbd.VecBiorbdMuscleStateDynamics(model.nbMuscleTotal())
act = MX.sym('act', 1, 1)
setAct = lambda vec,act : vec.setActivation(act)
for k in range(model.nbMuscleTotal()):
       setAct(VecSDyn[k], Act[k])
Result = model.muscularJointTorque(VecSDyn, State[:model.nbDof()], State[model.nbDof():])
```

And the error message is : 
```python
return _biorbd.Model_muscularJointTorque(self, state, Q, QDot)
TypeError: in method 'Model_muscularJointTorque', argument 3 of type 'biorbd::rigidbody::GeneralizedCoordinates const &'
```

My argument are Q and QDot, they are MX arguments and it is waiting for Generalized Coordinates. So, I look at in 'biorbd/include/RigidBody/GeneneralizedCoordinates.h, and because I use casadi-math (ligne 63, `#ifdef BIORBD_USE_CASADI_MATH`), it is waiting for MX casadi value.

I think so there is a problem. Think you for your future answers.

**Comment by pariterre** [comment]
Dear @Kilperic13 
Could you have a look at the last push of the #97 ?
I think it should solve your problem!
